# Generated by Django 5.1.4 on 2024-12-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerpointtemplate',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='powerpointtemplate',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_images/'),
        ),
        migrations.AlterField(
            model_name='powerpointtemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='powerpointtemplate',
            name='template_file',
            field=models.FileField(upload_to='ppt_templates/'),
        ),
    ]
