# Generated by Django 5.1.4 on 2024-12-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_powerpointtemplate_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerpointtemplate',
            name='thumbnail_image',
        ),
        migrations.AddField(
            model_name='powerpointtemplate',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='ppt_thumbnails/'),
            preserve_default=False,
        ),
    ]
